# Generated by Django 3.0.8 on 2020-07-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20200715_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=20, null=True),
        ),
    ]
